# -*- coding: utf-8 -*-
"""cGAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_spgt81HuvL0gDETmHRsWrbgFa0d4ph
"""

import tensorflow as tf
from tensorflow.keras import layers
import numpy as np
import matplotlib.pyplot as plt
import os

LATENT_DIM = 100
BATCH_SIZE = 128
EPOCHS = 400
LR = 2e-4

print("TensorFlow version:", tf.__version__)

def load_cifar10(batch_size):
    print("Loading CIFAR-10...")
    (x_train, _), _ = tf.keras.datasets.cifar10.load_data()
    x_train = x_train.astype("float32")
    x_train = (x_train - 127.5) / 127.5
    dataset = tf.data.Dataset.from_tensor_slices(x_train)
    dataset = dataset.map(
        lambda x: tf.image.random_flip_left_right(x),
        num_parallel_calls=tf.data.AUTOTUNE
    )
    dataset = dataset.shuffle(10000)
    dataset = dataset.batch(batch_size, drop_remainder=True)
    dataset = dataset.prefetch(tf.data.AUTOTUNE)

    return dataset

def build_generator():
    model = tf.keras.Sequential([
        layers.Dense(4*4*1024, use_bias=False, input_shape=(100,)),
        layers.BatchNormalization(),
        layers.ReLU(),
        layers.Reshape((4, 4, 1024)),

        layers.UpSampling2D(size=(2, 2)),
        layers.Conv2D(512, (3, 3), padding='same', use_bias=False),
        layers.BatchNormalization(),
        layers.ReLU(),

        layers.UpSampling2D(size=(2, 2)),
        layers.Conv2D(256, (3, 3), padding='same', use_bias=False),
        layers.BatchNormalization(),
        layers.ReLU(),

        layers.UpSampling2D(size=(2, 2)),
        layers.Conv2D(128, (3, 3), padding='same', use_bias=False),
        layers.BatchNormalization(),
        layers.ReLU(),

        layers.Conv2D(3, (3, 3), padding='same', use_bias=False, activation='tanh')
    ])
    return model

def build_discriminator():
    model = tf.keras.Sequential([
        layers.SpectralNormalization(layers.Conv2D(64, (5, 5), strides=(2, 2), padding='same', input_shape=[32, 32, 3])),
        layers.LeakyReLU(0.2),
        layers.Dropout(0.3),

        layers.SpectralNormalization(layers.Conv2D(128, (5, 5), strides=(2, 2), padding='same')),
        layers.BatchNormalization(),
        layers.LeakyReLU(0.2),
        layers.Dropout(0.3),

        layers.SpectralNormalization(layers.Conv2D(256, (5, 5), strides=(2, 2), padding='same')),
        layers.BatchNormalization(),
        layers.LeakyReLU(0.2),
        layers.Dropout(0.3),

        layers.SpectralNormalization(layers.Conv2D(512, (5, 5), strides=(2, 2), padding='same')),
        layers.BatchNormalization(),
        layers.LeakyReLU(0.2),
        layers.Dropout(0.3),

        layers.Flatten(),
        layers.SpectralNormalization(layers.Dense(1))
    ])
    return model

cross_entropy = tf.keras.losses.BinaryCrossentropy(from_logits=True)

def generator_loss(fake_output):
    return cross_entropy(tf.ones_like(fake_output), fake_output)

def discriminator_loss(real_output, fake_output):
    real_loss = cross_entropy(tf.ones_like(real_output) * 0.9, real_output)
    fake_loss = cross_entropy(tf.zeros_like(fake_output), fake_output)
    total_loss = real_loss + fake_loss
    return total_loss

def get_optimizers(lr=2e-4):
    generator_optimizer = tf.keras.optimizers.Adam(lr, beta_1=0.5, clipnorm=1.0)
    discriminator_optimizer = tf.keras.optimizers.Adam(lr, beta_1=0.5, clipnorm=1.0)
    return generator_optimizer, discriminator_optimizer

def generate_and_plot(generator,noise,epoch):

    images = generator(noise,training=False)

    images = (images+1)/2
    images = tf.clip_by_value(images,0,1)

    fig = plt.figure(figsize=(4,4))

    for i in range(images.shape[0]):
        plt.subplot(4,4,i+1)
        plt.imshow(images[i].numpy())
        plt.axis("off")

    plt.suptitle(f"Epoch {epoch}")
    plt.tight_layout()
    plt.show()

def train_gan():
    generator = build_generator()
    discriminator = build_discriminator()
    gen_opt, disc_opt = get_optimizers(LR)
    dataset = load_cifar10(BATCH_SIZE)

    fixed_noise = tf.random.normal([16, LATENT_DIM])

    @tf.function
    def train_step(real_images):
        noise = tf.random.normal([BATCH_SIZE, LATENT_DIM])
        real_images = real_images + tf.random.normal(tf.shape(real_images), stddev=0.05)

        with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:
            fake_images = generator(noise, training=True)
            real_output = discriminator(real_images, training=True)
            fake_output = discriminator(fake_images, training=True)

            gen_loss = generator_loss(fake_output)
            disc_loss = discriminator_loss(real_output, fake_output)

        gen_grads = gen_tape.gradient(gen_loss, generator.trainable_variables)
        disc_grads = disc_tape.gradient(disc_loss, discriminator.trainable_variables)

        gen_opt.apply_gradients(zip(gen_grads, generator.trainable_variables))
        disc_opt.apply_gradients(zip(disc_grads, discriminator.trainable_variables))

        return gen_loss, disc_loss

    @tf.function
    def generator_extra_step():
        noise = tf.random.normal([BATCH_SIZE, LATENT_DIM])

        with tf.GradientTape() as gen_tape:
            fake_images = generator(noise, training=True)
            fake_output = discriminator(fake_images, training=True)
            gen_loss = generator_loss(fake_output)

        grads = gen_tape.gradient(gen_loss, generator.trainable_variables)
        gen_opt.apply_gradients(zip(grads, generator.trainable_variables))

    print(f"Starting training for {EPOCHS} epochs...")

    for epoch in range(EPOCHS):
        for batch in dataset:
            g_loss, d_loss = train_step(batch)
            generator_extra_step()

        print(f"Epoch {epoch+1}/{EPOCHS} | G Loss: {g_loss:.4f} | D Loss: {d_loss:.4f}")

        if (epoch + 1) % 10 == 0:
            generate_and_plot(generator, fixed_noise, epoch + 1)

    return generator, discriminator

GAN_MODELS_DIR = './GAN_models/cGAN'
os.makedirs(GAN_MODELS_DIR, exist_ok=True)

generator_path = os.path.join(GAN_MODELS_DIR, 'generator.keras')
discriminator_path = os.path.join(GAN_MODELS_DIR, 'discriminator.keras')

if os.path.exists(generator_path) and os.path.exists(discriminator_path):
    print("Loading pre-trained models...")
    generator = tf.keras.models.load_model(generator_path, compile=False)
    discriminator = tf.keras.models.load_model(discriminator_path, compile=False)
    print("Models loaded successfully.")
else:
    print("No saved models found. Starting training...")
    generator, discriminator = train_gan()
    print("Training complete. Saving models...")
    generator.save(generator_path)
    discriminator.save(discriminator_path)
    print("Models saved successfully.")

noise = tf.random.normal([16,LATENT_DIM])
generate_and_plot(generator,noise,"Loaded Model")